### ISSUE TITLE
WithFragments::getHtml and asHtml don't allow an htmlSerializer to be passed

### ISSUE THREAD

**Issue by tremby** [prismicio/php-kit#105]
It would be useful if these methods could be passed an HTML serializer function, to pass through to any StructuredText fragments.

**Comment by tremby** [comment]
@jbdebiasio, please comment when you close something. Was this idea rejected? It's been done? Or what?

**Comment by arnaudlewis** [comment]
Hi @tremby, we’re about to release a new update of the php kit that will simplify the templating part. We’ll use this opportunity to allow the customization of the HTML. @jbdebiasio can tell you more about this if you have any specific question.

**Comment by jbdebiasio** [comment]
@tremby HTML serializer is already supported directly in the StructuredText class. For what reason do you want to pass HTML serializer inside these WithFragments method ? What is you use case?

In the coming next version of php-kit handling the prismic.io API v2, the class WithFragments is not useless anymore and so deleted.

**Comment by tremby** [comment]
I don't remember; this was almost three years ago. Might have been for a quick debug view of something, including the various transformations I'd built into an HTML serializer. Possibly for an admin panel? But it sounds like it's moot now.
