### ISSUE TITLE
Loosen version requirement for egeloen/http-adapter

### ISSUE THREAD

**Issue by cjunge-work** [prismicio/php-kit#111]
Currently the version of egeloen/http-adapter is locked specifically to 0.6.0, which prevents installing newer versions of Guzzle.

egeloen/http-adapter has been updated to support Guzzle 6, but the specific version of 0.6.0 does not have this support. Loosening this requirement to "~0.6.0" would allow updating to 0.8.

**Comment by erwan** [comment]
updated to 0.8.0
