### ISSUE TITLE
problem with prismicio oauth

### ISSUE THREAD

**Issue by eventhorizonpl** [prismicio/php-kit#119]
Hi,

We are using a prismicio oauth. The problem is that it doesn't work for newly created users (it was verified that it works ok on one old account). When I login it doesn't redirect me to my website. I can not find any support link on prismic.io.

In chrome inspector I see this
application.js:1633NOT FOUND /settings/authorizations/confirm?client_id=clientID&redirect_uri=http%3A%2F%2Fsomeapp.ngrok.io%2Fapp_dev.php%2Foauth%2Fcallback&scope=master%2Breleases&code=someCode/

Best regards,
Michal

@barrycarton

**Comment by erwan** [comment]
Hi,

OAuth is deprecated now, we recommend using the previews functionality instead:

https://prismic.io/docs/in-website-preview
