### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by gsteel** [prismicio/php-kit#120]
The Unit tests are failing because it seems that the test repository has been killed off:

    curl -I https://lesbonneschoses.cdn.prismic.io/api
    HTTP/1.1 301 Moved Permanently
    Location: https://prismic.io/docs/examples/blog

**Comment by erwan** [comment]
Yes, this is correct, we need to adapt the tests to remove the dependency on this repo.

**Comment by erwan** [comment]
fixed
