### ISSUE TITLE
[Question] Create documents via API

### ISSUE THREAD

**Issue by rogervila** [prismicio/php-kit#124]
Hello,

I can't find API method for create documents via API to Prismic on the [official documentation](https://prismic.io/docs/legacy/documentation/developers-manual) nor in the `\Prismic\Api` class.

Does this method exist?

Thank you.

**Comment by erwan** [comment]
Hi,

No, currently prismic.io doesn't have a write API.

**Comment by rogervila** [comment]
It would be amazing if you could add it, then I can implement it on the php-kit if you want.
