### ISSUE TITLE
APi Query is broken when Integration fields is activated

### ISSUE THREAD

**Issue by vianneyb** [prismicio/php-kit#164]
Hi,

when we have Integration fields activated, we noticed that the action parameter of the form already contains parameters, thus, the next piece of code isn't correct:

https://github.com/prismicio/php-kit/blob/adffceca6e89a0cdccd68fbfb6b64faa38034bee/src/Prismic/SearchForm.php#L273

This is what the action parameter look like:
https://test-repo.cdn.prismic.io/api/v1/documents/search?integrationFieldsRef=test-repo%7E4c145679-3af7-41ac-1234-12c120bc12d6

and this come from ApiData here:
https://github.com/prismicio/php-kit/blob/adffceca6e89a0cdccd68fbfb6b64faa38034bee/src/Prismic/Api.php#L333

Thx

**Comment by hypervillain** [comment]
Hey Vianney, thanks for reporting this! @arnaudlewis will take care of this in the coming days

**Comment by yoannblot** [comment]
Hi @hypervillain, @arnaudlewis, we are really willing to this feature, do you have any news about it ?

**Comment by Duaner** [comment]
This is fixed in the last version. 

Thanks for your patience.
