### ISSUE TITLE
Question: why md5 the cache key?

### ISSUE THREAD

**Issue by tremby** [prismicio/php-kit#83]
Just out of interest, is there any particular advantage to md5ing the URL to use as a cache key at https://github.com/prismicio/php-kit/blob/master/src/Prismic/SearchForm.php#L284 ? Why not just use the URL itself as the cache key? It'd make for easier debugging, and every cache implementation is storing it in a hashmap (and therefore hashing the key) anyway. You don't pre-hash it at https://github.com/prismicio/php-kit/blob/master/src/Prismic/Api.php#L294.

**Comment by tremby** [comment]
I still feel strongly about this, so I've made a pull request.

**Comment by rileyrg** [comment]
And years later I was asking the exact same question.
