### ISSUE TITLE
Missing getClient method : Previews not working

### ISSUE THREAD

**Issue by fireproofsocks** [prismicio/php-kit#93]
The current version of the Api.php class is missing the getClient function, so the preview functionality does not work:

````
The Call to undefined method Prismic\\Api::getClient() in /xxxvendor/prismic/php-sdk/src/Prismic/Api.php on line 213
````

See https://github.com/prismicio/php-kit/blob/cfa263f90c1307859baf81629f6e4c1ef017503f/src/Prismic/Api.php for when it was last there.

**Comment by erwan** [comment]
That's fixed, thanks for the report!
